title: 'Denver Bitcoin Developers'
tagline: 'Denver Bitcoin Developers is a meetup devoted to the research and development of Bitcoin'

menu:
  - {name: 'Events', url: '/events'}
  - {name: 'Meetup', url: 'https://www.meetup.com/denver-bitdevs/', external: true}
